### ISSUE TITLE
Accessibility issue with range

### ISSUE THREAD

**Issue by paulGeoghegan** [shoelace-style/webawesome-alpha#24]
### Describe the bug
A bug is _a demonstrable problem_ caused by code in the library. Please provide a clear and concise description of what the bug is here.
ranges are read correctly but the minvalue and maxvalue of them is not. This is especially important for disabled components since you can't manually check the minvalue or maxvalue.

### To Reproduce

1. Go to https://backers.webawesome.com/docs/components/range
2. Navigate to one of the range components while using a screen reader
3. The current range is read but the minvalue and maxvalue are not

      ### Browser / OS
       - OS: Windows
       - Browser: Firefox
       - Browser version: 127.0.1
       - Screen Reader: NVDA

**Comment by KonnorRogers** [comment]
@paulGeoghegan This _feels_ like a limitation of screenreaders using `<input type="range">`

We use the native HTMLElement and I can't get it to read min / max in Voiceover / NVDA.

https://codepen.io/paramagicdev/pen/mdYKEOZ

Is there perhaps some verbosity setting or keystroke combo I'm missing??

Or is this expected behavior?

**Comment by KonnorRogers** [comment]
Closing this as unfortunately this is browser / screenreader expected behavior.

I'll see if theres some nice pattern for exposing min / max values.

**Comment by paulGeoghegan** [comment]
@KonnorRogers fair enough and thanks.
