### ISSUE TITLE
Box-Sizing reset in applied.css may break layouts

### ISSUE THREAD

**Issue by whjvenyl** [shoelace-style/webawesome-alpha#49]
### Describe the bug
Having a `box-sizing: content-box` property somewhere in a parent element may break the intended layout due to the order of applied styles. The style definition in applied.css takes precedence over the definition in the host.

![CleanShot 2024-07-05 at 11  33 14@2x](https://github.com/shoelace-style/webawesome-alpha/assets/1174049/e6e17d60-e049-4508-a254-350689f3fae4)

### Demo

https://codepen.io/whjvenyl/pen/MWMgVrw

**Comment by claviska** [comment]
Thanks for reporting this. Applied Styles is technically a pro feature, but we shipped it for the alpha because we're actively using it for the docs.

Since Applied Styles are intended to be opinionated and opt-in, we'd like to keep this rule in place, so I've added `!important` to the host's styles. (I wish there were a better way to guarantee host styles.)
