### ISSUE TITLE
Drawer open = false don't work

### ISSUE THREAD

**Issue by altus34** [shoelace-style/webawesome-alpha#91]
### Describe the bug
When I try to hide the Drawer by setting the props "open" to false it doesn't work

### To Reproduce
Try to close the Drawer in JavaScript  but changing the prop value.

### Demo

drawer.setAttribute("open", "false");  doesnt't work
but
drawer.removeAttribute("open"); work

### Browser / OS
 - OS: Linux Ubuntu  22.04
 - Browser: Firefox
 - Browser version: 132

**Comment by KonnorRogers** [comment]
Shoelace treats Boolean attributes like the platform does.

Omission of an attribute is `false`, presence of an attribute is considered `true`.

just like `disabled`, `checked`, `selected`, `required` etc.

https://developer.mozilla.org/en-US/docs/Glossary/Boolean/HTML

> Note: The strings "true" and "false" are invalid values. To set the attribute to false, the attribute should be omitted altogether. Though modern browsers treat any string value as true, you should not rely on that behavior

Closing this as expected behavior!

**Comment by altus34** [comment]
So why not rename the property "opened" it will be more clear no ?

**Comment by KonnorRogers** [comment]
> So why not rename the property "opened" it will be more clear no ?

`<details>` element uses `open` so I don't see how it makes it anymore clear.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details#open
