### ISSUE TITLE
Font Awesome Icon not displaying when using `<wa-icon>` or `<wa-icon-button>`

### ISSUE THREAD

**Issue by goosedeersolutions** [shoelace-style/webawesome-alpha#98]
### Describe the bug
Font Awesome icons does not seem to be returning when adding via the `<wa-icon>` or `<wa-icon-button>`, however does work with the `<i>`, This was working a couple days ago. 

### To Reproduce
Steps to reproduce the behaviour:

1. Add kit to base.html file: `<script src="https://kit.fontawesome.com/<kit-token>.js" crossorigin="anonymous"></script>`
2. Add `<wa-icon name="house" variant="regular"></wa-icon>` to html
  2.1. No Icon displays. Getting 403 error in network tab of browser console.
3. Add `<i class="fa-regular fa-house"></i>`
  3.1 Icon displays as expected  

### Screenshots
have the following in my html file:

```
<i class="fa-regular fa-house"></i>
<wa-icon name="house" variant="regular"></wa-icon>
```

![image](https://github.com/user-attachments/assets/cf01f94a-3b74-4d86-8ed9-ce5047bebdac)

Bowser Console:

![image](https://github.com/user-attachments/assets/8cbc2602-5c2a-4052-a3fd-40f1a1aa2dc5)

### Browser / OS
 - OS: Windows
 - Browser: Chrome
 - Browser version: Version 131.0.6778.86 (Official Build) (64-bit)

### Additional information
It seems to be using `https://ka-f.fontawesome.com/releases/v6.5.2/svgs/regular/house.svg` to fetch the icon which is throwing the 403 http code.

If I change the version to `https://ka-f.fontawesome.com/releases/v6.7.1/svgs/regular/house.svg`, it is returning the icon as expected.

**Comment by claviska** [comment]
We're working on improving compatibility between FA and WA, but in the meantime have you seen this section of the docs?

https://backers.webawesome.com/docs/installation#using-font-awesome-kit-codes

This is how we recommend setting the FA kit code in Web Awesome because `<wa-icon>` doesn't use the typical Font Awesome library — it fetches the icons separately as SVGs, which is why it needs the kit code.

Let me know if that resolves it for you!

**Comment by KonnorRogers** [comment]
@goosedeersolutions 

The reason this is no longer working is because `<i class="fa-regular fa-house"></i>`

was accidentally included in certain versions of Font Awesome Free, even though it is a Pro icon. Assuming you're on a free Font Awesome kit code, this icon will most likely stop working once it gets properly removed from existing builds.

As @claviska stated, if you have a pro version of font awesome, I would follow the installation steps in the link he provided and that should get you squared away.

Apologies for the confusion!

**Comment by julianrubisch** [comment]
FWIW I'm a bit hesitant with kits because of GDPR concerns. I understand that this is out of scope for the alpha and I will gladly wait until an npm version lands so I can self-host it. Just wanted to make a note.
